### ISSUE TITLE
First Installation Error

### ISSUE THREAD

**Issue by vinaytaragi** [mojolab/mojobol#2]
Please check this
![error](https://user-images.githubusercontent.com/37395581/40224246-317eeab4-5aa3-11e8-9ddc-e71e4592e700.png)

E: Package 'zlib-bin' has no installation candidate
E: Package 'php5-mysql' has no installation candidate
E: Package 'php5' has no installation candidate

**Comment by arjunvenkatraman** [comment]
In the command that you are running, remove "zlib-bin" and replace php5 and php5-mysql with php and php-mysql respectively. Command will now read - 

apt-get install lame asterisk mysql-server wget gcc g++ bison zlib1g openssl php-mysql php apache2 python-mysqldb python-setuptools espeak python-dev git

**Comment by arjunvenkatraman** [comment]
Also, the section "Install codebase" below in the INSTALLATION file should read - 

Install codebase
======================================================
# cd /opt 
# git clone https://github.com/mojolab/mojobol.git
# cd mojobol
# sudo ln -s /opt/mojobol/bin /usr/share/asterisk/agi-bin/mojobol

**Comment by vinaytaragi** [comment]
![error2](https://user-images.githubusercontent.com/37395581/40224776-cb8b27b6-5aa4-11e8-8cbe-4607c92e171f.png)

EnvironmentError: mysql_config not found

**Comment by raviharshmehta** [comment]
E: Unable to correct problems, you have held broken packages.

![error](https://user-images.githubusercontent.com/39403488/40226908-a1124112-5aaa-11e8-93a3-6837193c7e6b.png)

**Comment by arjunvenkatraman** [comment]
Did you run 
sudo apt update 
sudo apt dist-upgrade

first?

If not, then please run these before proceeding

**Comment by raviharshmehta** [comment]
Sir ,
Same error ocurred.

**Comment by arjunvenkatraman** [comment]
The last error appears to be related to your installation and not mojobol. Please try the same steps on a clean installation of Ubuntu 16.04.

**Comment by arjunvenkatraman** [comment]
Re: mysql_config error, will log in and check this.

**Comment by arjunvenkatraman** [comment]
Also, please dont paste just the error, please also paste the command you ran

**Comment by arjunvenkatraman** [comment]
For the mysql error you need to run 
sudo mysql_secure_installation

and set your database username and password

**Comment by vinaytaragi** [comment]
OK. Now i run third cmd: 
sudo easy_install tweepy
and error is
ImportError: No module named pip.req

![error3](https://user-images.githubusercontent.com/37395581/40265210-a46f0924-5b51-11e8-8c21-3292062a856e.png)

**Comment by vinaytaragi** [comment]
error in this cmd
 sudo easy_install stopwatch

Searching for stopwatch
Reading https://pypi.python.org/simple/stopwatch/
No local packages or download links found for stopwatch
error: Could not find suitable distribution for Requirement.parse('stopwatch')

**Comment by arjunvenkatraman** [comment]
tweepy, simplejson and stopwatch are not needed any more. Those commands can be ignored.

**Comment by arjunvenkatraman** [comment]
You can use mojobol-svr-out.py instead of the sample.

**Comment by arjunvenkatraman** [comment]
I will update the installation doc once I have captured all the issues with the installation process. I think at this point we can do that. Will update and close this.
